name: 'Veracode Upload And Scan'

description: 'Upload files to veracode and start a static scan.'

inputs:
  appname:
    description: 'Name of the Application in the Veracode platform'
    required: false
    default: '${{ github.repository }}'
  createprofile:
    description: 'Create a new Application if none exists'
    required: false
    default: 'false'
  filepath:
    description: 'File(s) to upload'
    required: true
  scan_name:
    description: 'Name of the Scan'
    required: false
    default: 'Scan from Github job: ${{ github.run_id }}'
  vid:
    description: 'Veracode Secret ID'
    required: true
  vkey:
    description: 'Veracode Secret Key'
    required: true
  opt_args:
    description: 'Optional arguments for the java API Wrapper'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -appname 
    - ${{ inputs.appname }}
    - -createprofile 
    - ${{ inputs.createprofile }}
    - -filepath 
    - ${{ inputs.filepath }}
    - -scan_name 
    - ${{ inputs.scan_name }}
    - -vid 
    - ${{ inputs.vid }}
    - -vkey 
    - ${{ inputs.vkey }}
    - -opt_args 
    - ${{ inputs.opt_args}}
