# This is a basic workflow for testing this Action

name: testing

# Controls when the action will run. 
on: [push, workflow_dispatch]

jobs:
  upload:
    # run on linux
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout code
      uses: actions/checkout@v2

    - name: Veracode Upload and Scan Action Step
      uses: ./ # Uses an action in the root directory
      id: upload_and_scan
      with:
        appname: 'GitHub Action Testing'
        filepath: 'test_data/hello.jar'
        vid: '${{ secrets.VERACODE_ID }}'
        vkey: '${{ secrets.VERACODE_KEY }}'
